#!/bin/bash 
#Name:GitEnv
#Auther:hongyu
#Desc:
#Usage:
#Path:/home/hongyu/bin/EnvirmentConfig
#Update:Tue 28 Jul 2020 01:53:08 AM UTC

echo "export GIT_EDITOR=vim"
echo "export GIT_AUTHOR_NAME=Hongyu" >> ~/.bashrc
echo "export GIT_AUTHOR_EMAIL=hongsir1994@qq.com" >> ~/.bashrc
