#!/bin/bash 
#Name:GitEnv
#Auther:hongyu
#Desc:
#Usage:
#Path:/home/hongyu/bin
#Update:Mon 27 Jul 2020 02:38:36 PM UTC

export GIT_EDITOR=vim 
export GIT_AUTHOR_NAME=hongsir1994
export GIT_AUTHOR_EMAIL=hongsir1994@qq.com
git config --global diff.tool vimdiff
git config --global difftool.prompt false
git config --global alias.d difftool
