#!/bin/bash
#Name:vibash
#Desc:用来建立python脚本
#Usage:vibash [filename]
#Path:~/bin
#Update:2020-2-22

 if [ $# -ne 1 ]
 then
 	echo "Usage: vibash [filename]"
	exit 0
 fi

 if [ -f $1 ]
 then 
	echo "$1 is exit"
	vim $1
 else
	 touch $1
	 echo "#!/usr/bin/env python3 " >> $1
	 echo "#Name:$1" >> $1
	 echo "#Auther:$(whoami)" >> $1
	 echo "#Desc:" >> $1
	 echo "#Usage:" >> $1
	 echo "#Path:$(pwd)" >> $1
	 echo "#Update:$(date)" >> $1
	 vim $1
	 chmod u+x $1
fi
