#!/bin/bash 
#Name:
#Desc:
#Usage:
#Path:
#Update:

svn_config(){

	name=$(ls /home/.svn/)

	for temp in $name
	do
		cd /home/.svn/$temp/conf
		cat authz | sed '23aadmin=hongsir1994' | sed '28a[/]' | sed ' 30a@admin=rw' > authz_s
		mv authz_s authz

		cat passwd | sed '8ahongsir1994=105013hy' > passwd_s
		mv passwd_s passwd

		cat svnserve.conf | sed '19s/#//' | sed '20s/#//' | sed '27s/#//' | sed '36s/#//' | sed '19s/ //' | sed '20s/ //' | sed '36s/ //' | sed '27s/ //' | sed '66astore-passwords = yes'>  svnserve.conf_s
		mv svnserve.conf_s svnserve.conf
	done
}

svn_create(){
	file=$(cat ~/bin/svn.list)

	for temp in $file
	do
		svnadmin create /home/.svn/$temp
	done
}

svn_create
svn_config
